# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from scripts.core.bot_core import get_u2_device
from tkinter import *, messagebox, simpledialog, ttk
from typing import Any
from typing_extensions import Self
import cv2
import json
import numpy
import os
import sys
import tkinter

class SaveCropDialog:
    def __init__(self: Self, parent: Any) -> None: ...
    def on_ok(self: Self) -> Any: ...

class ADBCaptureWindow:
    def __init__(self: Self, parent: Any, sessions: Any, callback_add_item: Any) -> None: ...
    def build_ui(self: Self) -> Any: ...
    def refresh_devices(self: Self) -> Any: ...
    def capture_screen(self: Self) -> Any: ...
    def update_canvas(self: Self) -> Any: ...
    def on_mouse_down(self: Self, event: Any) -> Any: ...
    def on_mouse_drag(self: Self, event: Any) -> Any: ...
    def on_mouse_up(self: Self, event: Any) -> Any: ...
    def on_mouse_wheel(self: Self, event: Any) -> Any: ...
    def save_crop(self: Self) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import tkinter
import tkinter.ttk
import cv2
import numpy
import os
import json
import tkinter.simpledialog
import tkinter.messagebox
import scripts
import scripts.core
import scripts.core.bot_core
import sys
import subprocess
import ntpath