# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from flask import Flask, jsonify, request
from flask_cors import CORS
from flask_socketio import SocketIO
from typing import Any
import glob
import json
import logging
import os
import threading

def get_web_dir() -> Any:
    ...

gui_app_instance = None
def index() -> Any:
    ...

def get_ldplayers() -> Any:
    ...

def get_available_lds() -> Any:
    ...

def add_ldplayer() -> Any:
    ...

def get_scripts() -> Any:
    ...

def get_giao_cu_items() -> Any:
    ...

def start_bot() -> Any:
    ...

def stop_bot() -> Any:
    ...

def delete_bot() -> Any:
    ...

def pause_bot() -> Any:
    ...

def run_server(app_instance: Any) -> Any:
    ...

def start_api_thread(app_instance: Any) -> Any:
    ...

def get_logs(ld_name: Any) -> Any:
    ...

def select_ld() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import threading
import logging
import json
import glob
import os
import flask
import flask.Flask
import flask.jsonify
import flask.request
import flask_cors
import flask_cors.CORS
import flask_socketio
import flask_socketio.SocketIO
import sys
import ntpath
import traceback
import tkinter
import tkinter.messagebox