# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from scripts.core.sys_utils import SystemDiagnostic
from tkinter import messagebox
from typing import Any
import base64
import sys
import tkinter
import urllib.parse
import webbrowser

def show_auth_window() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import tkinter
import tkinter.messagebox
import sys
import webbrowser
import urllib
import urllib.parse
import base64
import scripts
import scripts.core
import scripts.core.sys_utils
import os
import json
import hashlib
import threading