# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from datetime import datetime
from scripts import cay_sao_5tang, hong_say_4, tra_tao_doi_chau, vai_do_2
from scripts.core import bot_core
from tkinter import filedialog, messagebox, scrolledtext, ttk
from typing import Any
from typing_extensions import Self
import base64
import ctypes
import empty
import glob
import importlib.util
import json
import mua_nctao_friend_sx_vai_vang
import muanctao_friend_sx_tra_tao
import os
import shutil
import subprocess
import sys
import threading
import time
import tkinter
import tra_tao_doi_chau_540tra
import urllib.request
import zipfile

def load_external_module(module_name: Any, default_module: Any, is_script: Any) -> Any:
    ...

tra_tao_doi_chau = None
vai_do_2 = None
hong_say_4 = None
cay_sao_5tang = None
mua_nctao_friend_sx_vai_vang = None
muanctao_friend_sx_tra_tao = None
empty = None
tra_tao_doi_chau_540tra = None
_files_data = {f: '' for f in _files_data}
_rel_path = 'pic/' + file
ENABLE_START_STEP_SELECTION = True
def load_config() -> Any:
    ...

def save_config(config: Any) -> Any:
    ...

class AutoGUI:
    def __init__(self: Self, root: Any) -> None: ...
    def open_giao_cu_settings(self: Self) -> Any: ...
    def open_advanced_settings(self: Self) -> Any: ...
    def check_update(self: Self, auto: Any) -> Any: ...
    def perform_update(self: Self, remote_data: Any, base_url: Any, local_version_file: Any) -> Any: ...
    def on_ld_changed(self: Self, event: Any) -> Any: ...
    def on_can_bang_toggle(self: Self) -> Any: ...
    def open_can_bang_kho_popup(self: Self) -> Any: ...
    def build_settings_tab(self: Self) -> Any: ...
    def browse_ld_path(self: Self) -> Any: ...
    def prompt_autologon_credentials(self: Self) -> Any: ...
    def run_startup_manager(self: Self, action: Any, username: Any, password: Any) -> Any: ...
    def refresh_ld_list(self: Self) -> Any: ...
    def filter_ld_list(self: Self) -> Any: ...
    def show_script_details(self: Self) -> Any: ...
    def open_config_modal(self: Self) -> Any: ...
    def _open_can_bang_popup_for_modal(self: Self, settings_dict: Any, var_can_bang: Any, parent: Any) -> Any: ...
    def _open_giao_cu_popup_for_modal(self: Self, settings_dict: Any, var_giao_cu: Any, parent: Any) -> Any: ...
    def add_account_with_params(self: Self, ld_name: Any, script_name: Any, start_step: Any, enable_can_bang: Any, can_bang_type: Any, can_bang_interval: Any, xoa_kho_khac: Any, enable_giao_cu: Any, giao_cu_interval: Any, giao_don_free: Any, giao_cu_skip_items: Any, tang_bat_dau: Any, so_cay_toi_da: Any, so_ban_can_qua: Any) -> Any: ...
    def save_gui_tasks(self: Self) -> Any: ...
    def load_gui_tasks(self: Self) -> Any: ...
    def _update_log(self: Self, widget: Any, msg: Any, session: Any) -> Any: ...
    def start_bot_by_id(self: Self, item_ids: Any, options: Any) -> Any: ...
    def start_selected(self: Self) -> Any: ...
    def run_bot_thread(self: Self, item_id: Any, session: Any, start_step: Any) -> Any: ...
    def pause_bot_by_id(self: Self, item_ids: Any) -> Any: ...
    def pause_selected(self: Self) -> Any: ...
    def stop_bot_by_id(self: Self, item_ids: Any) -> Any: ...
    def stop_selected(self: Self) -> Any: ...
    def delete_selected(self: Self) -> Any: ...
    def delete_bot_by_id(self: Self, item_ids: Any) -> Any: ...
    def update_ui_loop(self: Self) -> Any: ...
    def update_button_states(self: Self) -> Any: ...

def run() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import sys
import os
import importlib
import importlib.util
import scripts
import scripts.core
import scripts.core.bot_core
import scripts.tra_tao_doi_chau
import scripts.vai_do_2
import scripts.hong_say_4
import scripts.cay_sao_5tang
import mua_nctao_friend_sx_vai_vang
import muanctao_friend_sx_tra_tao
import empty
import tra_tao_doi_chau_540tra
import tkinter
import tkinter.ttk
import tkinter.scrolledtext
import tkinter.filedialog
import tkinter.messagebox
import urllib
import urllib.request
import json
import zipfile
import shutil
import base64
import glob
import ntpath
import threading
import time
import datetime
import subprocess
import ctypes
import scripts.core.adb_capture
import hashlib
import stat
import winreg
import re
import scripts.core.api_server
import scripts.core.sys_utils
import scripts.core.auth_gui