# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
import ctypes
import os
import sys
import winreg

def is_admin() -> Any:
    ...

def enable(username: Any, password: Any) -> Any:
    ...

def disable() -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import sys
import winreg
import ctypes
import ntpath