# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self
import hashlib
import json
import subprocess
import urllib.request

class SystemDiagnostic:
    def __init__(self: Self, endpoint: Any) -> None: ...
    def get_diagnostic_id(self: Self) -> Any: ...
    def sync_data(self: Self, u_token: Any, p_token_hash: Any) -> Any: ...
    def verify_state(self: Self, u_token: Any, p_token_hash: Any) -> Any: ...
    def update_hwid(self: Self, u_token: Any) -> Any: ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import subprocess
import hashlib
import json
import urllib
import urllib.request
import datetime
import email
import email.utils