# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from adbutils import sync
from typing import Any
from typing_extensions import Self
import ctypes
import cv2
import json
import numpy
import os
import queue
import subprocess
import sys
import threading
import time
import uiautomator2

original_popen = subprocess.Popen
class PatchedPopen(original_popen):
    def __init__(self: Self) -> None: ...

def get_base_path() -> Any:
    ...

class StopAutomation(Exception): ...
class RestartStepException(Exception): ...
class GameCrashException(Exception): ...
def kiem_tra_game_chay(session: Any) -> Any:
    ...

class BotSession:
    def __init__(self: Self, ld_name: Any) -> None: ...
    def log(self: Self, message: Any) -> Any: ...
    def load_daily_sales(self: Self) -> Any: ...
    def save_daily_sales(self: Self) -> Any: ...
    def check_midnight(self: Self) -> Any: ...
    def check_daily_reset(self: Self) -> Any: ...
    def check_state(self: Self) -> Any: ...

LD_INDEX_CACHE = {}
TEMPLATE_CACHE = {}
U2_DEVICE_CACHE = {}
LAST_SCREENSHOT_CACHE = {}
LAST_SCREENSHOT_TIME = {}
def get_ld_path() -> Any:
    ...

X_COORDS_ODD = [335, 490, 578, 645, 720, 835]
X_COORDS_EVEN = [335, 430, 505, 595, 665, 835]
Y_LAYERS = {1: 940, 2: 725, 3: 505, 4: 280, 5: 40}
START_POINT = (325, 799)
def get_drag_path(num_tree: int, start_layer: int) -> Any:
    ...

TOA_DO_O_SX = [(401, 718), (404, 836), (487, 834), (573, 833), (658, 835), (401, 917), (489, 919), (571, 917), (658, 916)]
TOA_DO_O_BAN = [(294, 430), (292, 625), (426, 437), (424, 624)]
may1 = (262, 917)
may2 = (254, 693)
diemchau1 = (397, 935)
diemchau2 = (393, 724)
region_ban = (6, 231, 965, 810)
region_nha_chinh = (553, 771, 886, 989)
region_san_xuat = (327, 541, 670, 780)
region_sua_bo = (69, 524, 256, 968)
vi_tri_kho_nong_san = (453, 366)
vi_tri_kho_thanh_pham = (446, 438)
def get_index_by_name(session: Any, name: Any) -> Any:
    ...

def get_u2_device(session: Any) -> Any:
    ...

def ld_tap(session: Any, x: Any, y: Any, times: Any) -> Any:
    ...

def _ld_swipe_core(session: Any, x1: Any, y1: Any, x2: Any, y2: Any, duration_ms: Any) -> Any:
    ...

def ld_swipe_bot_to_top(session: Any, x1: Any, y1: Any, x2: Any, y2: Any, duration: Any) -> Any:
    ...

def ld_swipe_by_speed(session: Any, x1: Any, y1: Any, x2: Any, y2: Any, speed: Any) -> Any:
    ...

def ld_swipe_right_to_left(session: Any, start_x: Any, y: Any, end_x: Any, duration: Any) -> Any:
    ...

def ld_swipe_floor(session: Any, floors: Any, duration: Any, retry_count: Any, check_tang: Any) -> Any:
    ...

def ld_send_key(session: Any, keycode: Any) -> Any:
    ...

def ld_drag_multi(session: Any, points: Any, duration: Any) -> Any:
    ...

def ld_drag_2_points(session: Any, x1: Any, y1: Any, x2: Any, y2: Any, speed: Any) -> Any:
    ...

def ld_sleep(session: Any, seconds: Any, interval: Any) -> Any:
    ...

def get_template(template_path: Any) -> Any:
    ...

def capture_screen_ld(session: Any) -> Any:
    ...

def find_image_ld(session: Any, template_path: Any, threshold: Any, region: Any, img_scene: Any, check_brightness: Any) -> Any:
    ...

def find_all_images_ld(session: Any, template_path: Any, threshold: Any, region: Any, img_scene: Any, check_brightness: Any) -> Any:
    ...

def check_images_at_coords(session: Any, template_path: Any, coords_list: Any, threshold: Any, check_brightness: Any, first_template_path: Any) -> Any:
    ...

def click_image_ld(session: Any, template_path: Any, threshold: Any, region: Any, check_brightness: Any) -> Any:
    ...

def check_and_close_level_up(session: Any) -> Any:
    ...

def giai_cuu_bot(session: Any, li_do: Any, can_bam_back: Any) -> Any:
    ...

def wait_pic(session: Any, pic_path: Any, threshold: Any, delay: Any, region: Any) -> Any:
    ...

def thuhoach_cactang(session: Any, pic_path: Any, so_diem: Any, diem_them: Any, duration: Any, vitri_tap: Any, tu_dong_dong_menu: Any, sanpham: Any, region: Any, kho: Any, vi_tri_kho: Any, threshold: Any, start_layer: Any) -> Any:
    ...

def thaotac_cactang(session: Any, pic_path: Any, tap_coords: Any, so_diem: Any, diem_them: Any, duration: Any, sanpham: Any, region: Any, kho: Any, vi_tri_kho: Any, threshold: Any, threshold_ban: Any, start_layer: Any) -> Any:
    ...

def doichau(session: Any, pic_path: Any, tap_coords: Any, quet_chong_sot: Any, so_lan_kho_full: Any) -> Any:
    ...

def sanxuat(session: Any, pic_path: Any, so_luong: Any, tap_coords: Any, threshold: Any, sleep_after_click: Any, speed: Any, tang_may: Any, sell_item: Any, from_storage: Any, threshold_item: Any) -> Any:
    ...

def ban(session: Any, sanpham: Any, kho: Any, vi_tri_kho: Any, threshold: Any, region: Any, so_lan: Any) -> Any:
    ...

def moruong(session: Any) -> Any:
    ...

def ban_vl_kho(session: Any, sanpham: Any, kho: Any, vi_tri_kho: Any, threshold: Any, region: Any, so_lan_ban: Any) -> Any:
    ...

def qua_nha_ban(session: Any) -> Any:
    ...

reader = None
def doc_so_luong_vat_lieu(session: Any, pic_path: Any) -> Any:
    ...

def san_xuat_cam(session: Any) -> Any:
    ...

def background_check_popup(session: Any) -> Any:
    ...

def xuong_nhachinh(session: Any) -> Any:
    ...

def kiem_tra_tac_vu_nen(session: Any) -> Any:
    ...

def khoi_dong_game_va_gia_lap(session: Any) -> Any:
    ...

def reset_bot_state(session: Any) -> Any:
    ...

def check_and_restart_game_if_needed(session: Any) -> Any:
    ...

def get_state_file(session: Any) -> Any:
    ...

def save_state(session: Any, step: Any, loop: Any) -> Any:
    ...

def load_state(session: Any) -> Any:
    ...

def clear_state(session: Any) -> Any:
    ...

DIGIT_TEMPLATES = None
def init_ocr() -> Any:
    ...

def read_number_with_templates(img_gray: Any, threshold: Any) -> Any:
    ...

def doc_so_luong_kho_vat_dung(session: Any, pic_path: Any) -> Any:
    ...

def nang_cap_kho(session: Any, kho: Any) -> Any:
    ...

def can_bang_kho(session: Any, kho: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import os
import ctypes
import adbutils
import adbutils.sync
import subprocess
import cv2
import numpy
import time
import uiautomator2
import sys
import ntpath
import threading
import queue
import json
import math
import glob