# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from bot_core import *, find_image_ld, khoi_dong_game_va_gia_lap, ld_sleep, ld_swipe_floor, qua_nha_ban, sanxuat, thaotac_cactang, xuong_nhachinh
from threading import ThreadError
from typing import Any

def step1_trong_va_sx_hongsay(session: Any, start_loop: Any) -> Any:
    ...

def step2_ban_hong_say(session: Any) -> Any:
    ...

def run_bot(session: Any, start_step: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import bot_core
import threading