# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from bot_core import *, find_image_ld, khoi_dong_game_va_gia_lap, ld_sleep, qua_nha_ban, sanxuat, xuong_nhachinh
from threading import ThreadError
from typing import Any

def step1_ban_vai_do(session: Any) -> Any:
    ...

def step2_sx_vai_do(session: Any, start_loop: Any) -> Any:
    ...

def run_bot(session: Any, start_step: Any) -> Any:
    ...


__name__ = ...



# Modules used internally, to allow implicit dependencies to be seen:
import bot_core
import threading